project:
  type: website
  output-dir: docs
  resources:
    - assets/*

website:
  title: "soma stuff"
  site-url: https://jonathansoma.com/words/
  open-graph:
    locale: en_US
    image: "https://jonathansoma.com/words/assets/where-are-things.png"
  twitter-card:
    creator: "@dangerscarf"
    image: "https://jonathansoma.com/words/assets/where-are-things.png"
  google-analytics: G-1W7890GDTM

format:
  html:
    toc-title: Contents
    css: style.css
    theme: cosmo
    title-block: none
    title-block-banner: "#fff880"
    title-block-banner-color: black
